-- Tax Processing Database Queries
-- Legacy DB2 SQL for Federal Tax System
-- Used by COBOL batch processing and Java web services

-- Query 1: Retrieve taxpayer information for tax calculation
SELECT 
    T.TAXPAYER_ID,
    T.SSN,
    T.FIRST_NAME,
    T.LAST_NAME,
    T.DATE_OF_BIRTH,
    T.FILING_STATUS,
    T.IS_MARRIED,
    T.IS_HEAD_OF_HOUSEHOLD,
    T.SPOUSE_SSN,
    TR.TAX_YEAR,
    TR.GROSS_INCOME,
    TR.WAGES_W2,
    TR.INTEREST_INCOME,
    TR.DIVIDEND_INCOME,
    TR.OTHER_INCOME,
    TD.NUMBER_OF_DEPENDENTS,
    TD.NUMBER_OF_CHILDREN_UNDER_17,
    TD.NUMBER_OF_QUALIFYING_CHILDREN_EIC
FROM 
    TAXDB.TAXPAYERS T
    INNER JOIN TAXDB.TAX_RETURNS TR ON T.TAXPAYER_ID = TR.TAXPAYER_ID
    LEFT JOIN TAXDB.TAX_DEPENDENTS TD ON TR.RETURN_ID = TD.RETURN_ID
WHERE 
    T.TAXPAYER_ID = ?
    AND TR.TAX_YEAR = ?
    AND TR.RETURN_STATUS IN ('FILED', 'PROCESSING', 'AMENDED');

-- Query 2: Insert tax calculation results
INSERT INTO TAXDB.TAX_CALCULATIONS 
(
    CALCULATION_ID,
    RETURN_ID,
    TAXPAYER_ID,
    TAX_YEAR,
    GROSS_INCOME,
    ADJUSTED_GROSS_INCOME,
    STANDARD_DEDUCTION,
    ITEMIZED_DEDUCTION,
    DEDUCTION_TYPE,
    TAXABLE_INCOME,
    FEDERAL_TAX_BEFORE_CREDITS,
    CHILD_TAX_CREDIT,
    EARNED_INCOME_CREDIT,
    EDUCATION_CREDITS,
    OTHER_CREDITS,
    TOTAL_CREDITS,
    NET_TAX_LIABILITY,
    FEDERAL_TAX_WITHHELD,
    ESTIMATED_TAX_PAYMENTS,
    REFUND_DUE,
    AMOUNT_OWED,
    CALCULATION_DATE,
    CALCULATED_BY_SYSTEM,
    CALCULATION_STATUS
)
VALUES 
(
    ?,  -- CALCULATION_ID (generated sequence)
    ?,  -- RETURN_ID
    ?,  -- TAXPAYER_ID
    ?,  -- TAX_YEAR
    ?,  -- GROSS_INCOME
    ?,  -- ADJUSTED_GROSS_INCOME
    ?,  -- STANDARD_DEDUCTION
    ?,  -- ITEMIZED_DEDUCTION
    ?,  -- DEDUCTION_TYPE ('STANDARD' or 'ITEMIZED')
    ?,  -- TAXABLE_INCOME
    ?,  -- FEDERAL_TAX_BEFORE_CREDITS
    ?,  -- CHILD_TAX_CREDIT
    ?,  -- EARNED_INCOME_CREDIT
    ?,  -- EDUCATION_CREDITS
    ?,  -- OTHER_CREDITS
    ?,  -- TOTAL_CREDITS
    ?,  -- NET_TAX_LIABILITY
    ?,  -- FEDERAL_TAX_WITHHELD
    ?,  -- ESTIMATED_TAX_PAYMENTS
    ?,  -- REFUND_DUE
    ?,  -- AMOUNT_OWED
    CURRENT_TIMESTAMP,  -- CALCULATION_DATE
    ?,  -- CALCULATED_BY_SYSTEM ('COBOL_BATCH' or 'WEB_SERVICE')
    ?   -- CALCULATION_STATUS ('COMPLETED', 'ERROR', 'PENDING_REVIEW')
);

-- Query 3: Retrieve tax bracket information for given tax year
SELECT 
    TB.TAX_YEAR,
    TB.FILING_STATUS,
    TB.BRACKET_NUMBER,
    TB.INCOME_THRESHOLD_MIN,
    TB.INCOME_THRESHOLD_MAX,
    TB.TAX_RATE,
    TB.BASE_TAX_AMOUNT,
    TB.EFFECTIVE_DATE,
    TB.EXPIRATION_DATE
FROM 
    TAXDB.TAX_BRACKETS TB
WHERE 
    TB.TAX_YEAR = ?
    AND TB.FILING_STATUS = ?
    AND TB.EFFECTIVE_DATE <= CURRENT_DATE
    AND (TB.EXPIRATION_DATE IS NULL OR TB.EXPIRATION_DATE >= CURRENT_DATE)
ORDER BY 
    TB.BRACKET_NUMBER;

-- Query 4: Retrieve standard deduction amounts
SELECT 
    SD.TAX_YEAR,
    SD.FILING_STATUS,
    SD.STANDARD_DEDUCTION_AMOUNT,
    SD.ADDITIONAL_DEDUCTION_65_OVER,
    SD.ADDITIONAL_DEDUCTION_BLIND,
    SD.EFFECTIVE_DATE
FROM 
    TAXDB.STANDARD_DEDUCTIONS SD
WHERE 
    SD.TAX_YEAR = ?
    AND SD.FILING_STATUS = ?
    AND SD.EFFECTIVE_DATE <= CURRENT_DATE
ORDER BY 
    SD.EFFECTIVE_DATE DESC
FETCH FIRST 1 ROW ONLY;

-- Query 5: Retrieve credit information (Child Tax Credit, EIC, etc.)
SELECT 
    TC.TAX_YEAR,
    TC.CREDIT_TYPE,
    TC.CREDIT_NAME,
    TC.MAX_CREDIT_AMOUNT,
    TC.INCOME_PHASE_OUT_START,
    TC.INCOME_PHASE_OUT_COMPLETE,
    TC.PHASE_OUT_RATE,
    TC.FILING_STATUS_ELIGIBLE,
    TC.MIN_AGE_REQUIREMENT,
    TC.MAX_AGE_REQUIREMENT,
    TC.RESIDENCY_TEST_REQUIRED,
    TC.RELATIONSHIP_TEST_REQUIRED
FROM 
    TAXDB.TAX_CREDITS TC
WHERE 
    TC.TAX_YEAR = ?
    AND TC.CREDIT_TYPE IN ('CHILD_TAX_CREDIT', 'EARNED_INCOME_CREDIT')
    AND TC.EFFECTIVE_DATE <= CURRENT_DATE
    AND (TC.EXPIRATION_DATE IS NULL OR TC.EXPIRATION_DATE >= CURRENT_DATE)
ORDER BY 
    TC.CREDIT_TYPE;

-- Query 6: Audit query for tax calculation validation
SELECT 
    TC.TAXPAYER_ID,
    TC.TAX_YEAR,
    TC.GROSS_INCOME,
    TC.TAXABLE_INCOME,
    TC.FEDERAL_TAX_BEFORE_CREDITS,
    TC.TOTAL_CREDITS,
    TC.NET_TAX_LIABILITY,
    TC.CALCULATION_DATE,
    TC.CALCULATED_BY_SYSTEM,
    -- Recalculate federal tax using current brackets for comparison
    (SELECT SUM(
        CASE 
            WHEN TC.TAXABLE_INCOME > TB.INCOME_THRESHOLD_MIN 
            THEN 
                LEAST(TC.TAXABLE_INCOME, COALESCE(TB.INCOME_THRESHOLD_MAX, TC.TAXABLE_INCOME)) 
                - TB.INCOME_THRESHOLD_MIN + 1
            ELSE 0 
        END * TB.TAX_RATE / 100
    ) + COALESCE(
        (SELECT SUM(TB2.BASE_TAX_AMOUNT) 
         FROM TAXDB.TAX_BRACKETS TB2 
         WHERE TB2.TAX_YEAR = TC.TAX_YEAR 
         AND TB2.BRACKET_NUMBER < TB.BRACKET_NUMBER), 0)
     FROM TAXDB.TAX_BRACKETS TB 
     WHERE TB.TAX_YEAR = TC.TAX_YEAR 
     AND TB.FILING_STATUS = (SELECT FILING_STATUS FROM TAXDB.TAXPAYERS WHERE TAXPAYER_ID = TC.TAXPAYER_ID)
     AND TC.TAXABLE_INCOME >= TB.INCOME_THRESHOLD_MIN) AS RECALCULATED_TAX,
    -- Flag potential discrepancies
    CASE 
        WHEN ABS(TC.FEDERAL_TAX_BEFORE_CREDITS - (
            SELECT SUM(
                CASE 
                    WHEN TC.TAXABLE_INCOME > TB.INCOME_THRESHOLD_MIN 
                    THEN 
                        LEAST(TC.TAXABLE_INCOME, COALESCE(TB.INCOME_THRESHOLD_MAX, TC.TAXABLE_INCOME)) 
                        - TB.INCOME_THRESHOLD_MIN + 1
                    ELSE 0 
                END * TB.TAX_RATE / 100
            ) FROM TAXDB.TAX_BRACKETS TB 
            WHERE TB.TAX_YEAR = TC.TAX_YEAR 
            AND TC.TAXABLE_INCOME >= TB.INCOME_THRESHOLD_MIN
        )) > 1.00 THEN 'REVIEW_REQUIRED'
        ELSE 'OK'
    END AS VALIDATION_STATUS
FROM 
    TAXDB.TAX_CALCULATIONS TC
WHERE 
    TC.TAX_YEAR = ?
    AND TC.CALCULATION_DATE >= CURRENT_DATE - 7 DAYS
    AND TC.CALCULATION_STATUS = 'COMPLETED'
ORDER BY 
    TC.CALCULATION_DATE DESC;
